### ISSUE TITLE
[Feature] Parse file backwards

### ISSUE THREAD

**Issue by RoboMagus** [larsjuhw/OctoPrint-SlicerSettingsParser#3]
**Is your feature request related to a problem? Please describe.**
Not a huge problem, but when analyzing _all_ of my uploaded GCode files I noticed parsing took a really long time. There are options to limit the number of lines parsed, but since PrusaSlicer puts all slicer settings at the end of the file that does not help in my situation.

**Describe the solution you'd like**
The option to parse the file in reverse (starting at the last line and working up).
This together with the line limit (or until an actual GCode line is hit) should speedup processing significantly.

**Describe alternatives you've considered**
Waiting it out. But where's the fun in that 😄

**Comment by Felipe-NS** [comment]
Good idea. Some of my programs don't work here because the time to read is too long.
To improve your idea, I think make parsing capable of detecting when the gcode is from Prusa and automatic do the reverse.

**Comment by RoboMagus** [comment]
@Felipe-NS, I like the idea of searching both top to bottom and bottom to top until the limits are reached. That would be a nice extension upon the PR i've just opened. For now i've left that out in order to limit the impact of the change.

In order to integrate the bidirectional search with the existing search limit options we should think of how to represent the settings to the user.
