### ISSUE TITLE
[Bug] wrong regex example for Cura

### ISSUE THREAD

**Issue by Ingegneus** [larsjuhw/OctoPrint-SlicerSettingsParser#7]
not really a bug, but in the readme of the repo there is the regex example for Cura, when using [CuraSettingsInjector.gcode](https://gist.github.com/tjjfvi/75210b2ed20ed194d6eab48bf70c4f12). the regex uses a ":" instead of "="

**Comment by larsjuhw** [comment]
Yes, updated now. Thanks!
